service: resnet34-pytorch-example

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-south-1
  timeout: 60
  environment:
    S3_BUCKET: tsai-models-s1-mou
    MODEL_PATH: resnet34.pt
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:getObject"
      Resource: "arn:aws:s3:::tsai-models-s1-mou/*"

custom:
   pythonRequirements:
      dockerizePip: true
      zip: true
      slim: true
      strip: false
      noDeploy:
        - docUtils
        - jmespath
        - pip
        - python-dateutil
        - setuptools
        - six
        - tensorboard
      useStaticCache : true
      useDownloadCache: true
      cacheLocation: "./cache"  


# you can add packaging information here
package:
 individually : false
 exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - cache/**
    - test/**
    - __pycache__/**
    - .pytest-cache/**
    - model/**
    - models/**
    - venv/**
    - .requirement.zip
    - .serverless/**
    
functions:
  classify_image:
    handler: handler.classify_image
    memorysize: 3008
    timeout: 60
    events:
      - http:
          path: classify
          method: post
          cors: true

plugins:
  - serverless-python-requirements
